### ISSUE TITLE
Getting error while using persistent layout settings 

### ISSUE THREAD

**Issue by iabduul7** [JeffreyWay/Build-Modern-Laravel-Apps-With-Inertia#2]
Hi @JeffreyWay 
can you please help me in this. I am following your series and i was working on my app locally and when I am trying to use persistent layout (`layout: AppLoyout`) I am having this error in `npm run prod`

`
ERROR in ./resources/js/Pages/Dashboard.vue?vue&type=template&id=b02f0a66 (./node_modules/babel-loader/lib/index.js??clonedRuleSet-5.use[0]!./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1
].rules[2]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./resources/js/Pages/Dashboard.vue?vue&type=template&id=b02f0a66)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
TypeError: Cannot read property 'type' of undefined
    at genNode (C:\Users\abdul\PhpstormProjects\practice-app\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2568:18)
    at genNode (C:\Users\abdul\PhpstormProjects\practice-app\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2572:13)
    at genNodeList (C:\Users\abdul\PhpstormProjects\practice-app\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2546:13)
    at genNodeListAsArray (C:\Users\abdul\PhpstormProjects\practice-app\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2531:5)
    at genNodeList (C:\Users\abdul\PhpstormProjects\practice-app\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2543:13)
    at genVNodeCall (C:\Users\abdul\PhpstormProjects\practice-app\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2701:5)
    at genNode (C:\Users\abdul\PhpstormProjects\practice-app\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2593:13)
    at generate (C:\Users\abdul\PhpstormProjects\practice-app\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2355:9)
    at Object.baseCompile (C:\Users\abdul\PhpstormProjects\practice-app\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:5540:12)
    at Object.compile (C:\Users\abdul\PhpstormProjects\practice-app\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.prod.js:3020:25)
`

**Comment by iabduul7** [comment]
it is the issue with named slots and persitent layout [issue 171 on inertisjs repo](https://github.com/inertiajs/inertia/issues/171)

**Comment by rachids** [comment]
try to update vue loader
```bash
npm update vue-loader
```

**Comment by salmanjaveed** [comment]
@iabduul7 could it be a typo at (layout: AppLoyout) instead of (layout: AppLayout)
